### ISSUE TITLE
is 'core field' required?

### ISSUE THREAD

**Issue by wdduncan** [BeBOP-OBON/miop#12]
The description for the slot `core field` says:  
```
MIOP field determined to be essential across all protocols
```
Do you mean for this to be a required field? If so, the slot should be:
```
core field:
    required: true
```
cc @pbuttigieg

**Comment by raissameyer** [comment]
@wdduncan thanks for bringing this up. 

With MIOP we are following a similar structure as MIxS, in that we will have a core list of terms and then packages as needed (e.g. an OBON package with additional terms that would be relevant to the OBON programme).

Within the collection of core fields, some will be mandatory and others will be optional.
